/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

#import <Foundation/NSObject.h>

@interface LSApplicationWorkspace : NSObject {
}
+ (id)defaultWorkspace;	// 0xc9c8
- (id)applicationsAvailableForOpeningDocument:(id)openingDocument;	// 0xc6c8
- (id)operationToOpenResource:(id)openResource usingApplication:(id)application uniqueDocumentIdentifier:(id)identifier userInfo:(id)info;	// 0xadc4
- (id)operationToOpenResource:(id)openResource usingApplication:(id)application uniqueDocumentIdentifier:(id)identifier userInfo:(id)info delegate:(id)delegate;	// 0xadf8
- (id)operationToOpenResource:(id)openResource usingApplication:(id)application userInfo:(id)info;	// 0xad90
- (BOOL)registerApplication:(id)application;	// 0xc8bc
- (BOOL)unregisterApplication:(id)application;	// 0xc8dc
@end

